#pragma once


#define TAM_HOR_ABA_LOG_TEXTO 50
#define TAM_VER_ABA_LOG_TEXTO 13
#define POS_HOR_ABA_LOG_TEXTO 25
#define POS_VER_ABA_LOG_TEXTO 7
#define POS_HOR_TABULEIRO 1
#define POS_VER_TABULEIRO 7
#define TAM_HOR_TABULEIRO 20
#define TAM_VER_TABULEIRO 17
#define TAM_HOR_PECA 6
#define TAM_VER_PECA 5

//http://www.asciitable.com/
#define CHAR_RETA_VERTICAL 179
#define CHAR_RETA_HORIZONTAL 196
#define CHAR_COTOVELO_CIMA_DIREITO 192
#define CHAR_COTOVELO_CIMA_ESQUERDO 217
#define CHAR_COTOVELO_BAIXO_ESQUERDO 191
#define CHAR_COTOVELO_BAIXO_DIREITO 218
#define CHAR_LIGA_CIMA_ESQUERDA_BAIXO 180
#define CHAR_LIGA_CIMA_ESQUERDA_DIREITA 193
#define CHAR_LIGA_CIMA_DIREITA_BAIXO 195
#define CHAR_LIGA_BAIXO_EQUERDA_DIREITA 194
#define CHAR_LIGA_TODOS 197

#define CHAR_SOMBRA_0 32
#define CHAR_SOMBRA_25 176
#define CHAR_SOMBRA_50 177
#define CHAR_SOMBRA_75 178
#define CHAR_SOMBRA_100 219